language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed huynhnv2/udagram-api-feed:v2
  - docker tag udagram-api-user huynhnv2/udagram-api-user:v2
  - docker tag udagram-frontend huynhnv2/udagram-frontend:v2
  - docker tag reverseproxy huynhnv2/reverseproxy:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push huynhnv2/udagram-api-feed:v2
  - docker push huynhnv2/udagram-api-user:v2
  - docker push huynhnv2/udagram-frontend:v2
  - docker push huynhnv2/reverseproxy:v2